### ISSUE TITLE
Google photostats photocrash

### ISSUE THREAD

**Issue by medichylton** [wizages/CleanSheets#12]
Please blacklist Google photos as well

**Comment by wizages** [comment]
I am having no issue with google photos so I am not blacklisting or developing a fix for it until I see a crash.

**Comment by wizages** [comment]
When creating a collage and then click share crashes the app.

**Comment by wizages** [comment]
Fixed in: https://github.com/wizages/CleanSheets/commit/9395e7c22964cb19323176747fa8587bd10b6379
